import { useState } from "react";
import ButtonAlt from "../components/ButtonAlt";
import { v4 as uuidv4 } from "uuid";
import Tooltip from "../components/Tooltip";
import AdminTopPanel from "../components/AdminTopPanel";
import AdminUpdatePanel from "../components/AdminUpdatePanel";

const Admin = () => {
  const [viewReport, setViewReport] = useState(0);
  const [data, setData] = useState<any[]>([]);
  const reports = [
    "Find the total revenue for each month in the past year and a super-aggregate row with the overall revenue",
    "Show the total revenue generated by each category of medicine in the last 6 months, including a summary row that shows the overall total revenue.",
    "Show the total revenue for each customer status and also the overall revenue",
    "Show the total revenue generated by each customer in each month of the last year, including a summary row that shows the overall total revenue for all customers in each month.",
  ];

  const report = async (id: number) => {
    setViewReport(id);
    const response = await fetch("http://localhost:2003/api/report/" + id);
    const fetchData = await response.json();
    console.log(fetchData);
    setData(fetchData.data);
  };

  const showData = () => {
    if (viewReport == 1 && data != null && data != undefined) {
      if (data[0]?.month) {
        return (
          <div className="flex w-200 items-center justify-center">
            <div className="grid w-full grid-cols-3 gap-x-6 gap-y-10">
              {data.map((m) => {
                return (
                  <div
                    key={uuidv4()}
                    className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl transition-all delay-100 duration-300 ease-in hover:scale-105"
                  >
                    <h2 className="text-md text-gray-300">
                      {m.month ? m.month : "Total revenue"}
                    </h2>
                    <p className="pt-8 text-3xl font-semibold text-gray-200">
                      ₹ {m.revenue}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        );
      }
    } else if (viewReport == 2 && data != null && data != undefined) {
      if (data[0]?.m_category) {
        return (
          <div className="flex w-200 items-center justify-center">
            <div className="grid w-full grid-cols-3 gap-x-6 gap-y-10">
              {data.map((m) => {
                return (
                  <div
                    key={uuidv4()}
                    className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl transition-all delay-100 duration-300 ease-in hover:scale-105"
                  >
                    <h2 className="text-md text-gray-300">
                      {m.month ? m.month : "Total revenue"}
                    </h2>
                    <p className="pt-6 text-center text-lg text-gray-200">
                      {m.m_category}
                    </p>
                    <p className="pt-8 text-3xl font-semibold text-gray-200">
                      ₹ {m.revenue}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        );
      }
    } else if (viewReport == 3 && data != null && data != undefined) {
      if (data[0]?.revenue) {
        return (
          <div className="flex w-200 items-center justify-center">
            <div className="grid w-full grid-cols-3 gap-x-6">
              <div className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl">
                <h2 className="text-lg text-gray-300">Normal Revenue</h2>
                <p className="pt-8 text-2xl font-semibold text-gray-200">
                  ₹ {data[0].revenue}
                </p>
              </div>
              <div className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl">
                <h2 className="text-lg text-gray-300">VIP Revenue</h2>
                <p className="pt-8 text-2xl font-semibold text-gray-200">
                  ₹ {data[1].revenue}
                </p>
              </div>
              <div className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl">
                <h2 className="text-lg text-gray-300">Total Revenue</h2>
                <p className="pt-8 text-2xl font-semibold text-gray-200">
                  ₹ {data[2].revenue}
                </p>
              </div>
            </div>
          </div>
        );
      }
    } else if (viewReport == 4 && data != null && data != undefined) {
      if (data[0]?.c_id) {
        return (
          <div className="flex w-200 items-center justify-center">
            <div className="grid w-full grid-cols-3 gap-x-6 gap-y-10">
              {data.map((c) => {
                return (
                  <div
                    key={uuidv4()}
                    className="flex flex-col items-center rounded-2xl bg-neutral-700 px-4 py-10 shadow-xl"
                  >
                    <h2 className="text-lg text-gray-300">
                      {c.month ? c.month : "Total revenue"}
                    </h2>
                    <p className="pt-6 text-sm text-slate-300">
                      Customer {c.c_id}
                    </p>
                    <p className="pt-8 text-3xl font-semibold text-gray-200">
                      ₹ {c.revenue}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        );
      }
    }
  };

  return (
    <>
      <AdminTopPanel />
      <AdminUpdatePanel />
      <div className="mx-8 my-32 flex w-full flex-col items-center justify-center">
        <div className="min-w-100 flex flex-row items-center justify-center gap-x-10">
          <Tooltip text={reports[0] as string}>
            <ButtonAlt onClick={() => report(1)} view={viewReport} bid={1}>
              Report 1
            </ButtonAlt>
          </Tooltip>
          <Tooltip text={reports[1] as string}>
            <ButtonAlt onClick={() => report(2)} view={viewReport} bid={2}>
              Report 2
            </ButtonAlt>
          </Tooltip>
          <Tooltip text={reports[2] as string}>
            <ButtonAlt onClick={() => report(3)} view={viewReport} bid={3}>
              Report 3
            </ButtonAlt>
          </Tooltip>
          <Tooltip text={reports[3] as string}>
            <ButtonAlt onClick={() => report(4)} view={viewReport} bid={4}>
              Report 4
            </ButtonAlt>
          </Tooltip>
        </div>
        <div className="pt-50">
          {viewReport != 0 && data != null && <>{showData()}</>}
        </div>
      </div>
    </>
  );
};

export default Admin;
